### ISSUE TITLE
mtpy-data link not working

### ISSUE THREAD

**Issue by camsshepherd** [MTgeophysics/mtpy-v2#23]
Copying an issue posted in the old mtpy repository that I am also having. I want to create my own MT_collection with my MT_data. When I look for how to create it, the link created for the (mtpy_data) at below, does not open.

https://github.com/MTgeophysics/mtpy_data

Test data can be found at [mtpy-data](https://github.com/MTgeophysics/mtpy_data). Installation instructions are included in README.

from mtpy_data import GRID_LIST, PROFILE_LIST

Initiate MTCollection
from pathlib import Path
from mtpy import MT, MTCollection

2023-04-14 11:48:00,318 [line 135] mth5.setup_logger - INFO: Logging file can be found C:\Pathway\debug.log

mtc = MTCollection()
mtc.open_collection(Path().cwd().joinpath("test_mt_collection.h5"))

**Comment by kujaku11** [comment]
@camsshepherd Did you get this to work or is there still an issue?  Could you post the error if there is one?

**Comment by kujaku11** [comment]
@camsshepherd Made the `mtpy_data` repository public and added a few more forward model data sets.  It is installable but not on PyPi yet.  So I would clone the repo and then `pip install -e .`
